### ISSUE TITLE
for cbrain boutiques descriptor, declare all input files as input files

### ISSUE THREAD

**Issue by MontrealSergiy** [CorentinLabelle/Brainstorm-Tool#33]
presently json file with pipeline config is string. To work smoothly in CBRAIN all files should be declared as such file inputs, including json, and any files mentioned within json.

Note 1 Mind CBRAIN runs on different HPC clusters, so, normally, users are supposed to upload all data to CBRAIN rather than their own folders on cluster. CBRAIN will copy said files to appropriate cluster when needed.

Note 2 There could be exceptions, e.g. if `<pipelinepath>.json` is already in bids folder, yet it would contradict bids specs I think

**Comment by CorentinLabelle** [comment]
I changed the input type in the boutique descriptor (10.5072/zenodo.1182898). The json with the pipeline config is now a 'File'.

About the Note 2, I'm not sure I understand what you mean. Which file are you referring to by ".json" ?
The json file containing the pipeline config should not be in the BIDS folder.

**Comment by christinerogers** [comment]
super @CorentinLabelle 

1 -- how soon can you update your tool's code to match? 

> About the Note 2, I'm not sure I understand what you mean. Which file are you referring to by ".json" ?
> The json file containing the pipeline config should not be in the BIDS folder.

It's a good thing to clarify -
2 - Corentin can you confirm what happens when you run your output on the BIDS Validator and let us know? 

cc @andesha

**Comment by MontrealSergiy** [comment]
if json pipeline config file not in BIDS folder you can totally ignore Note 2. 

I actually typed `<pipelinepath>.json` yet, for some reason github ate pipelinepath. I apologise for that.

**Comment by MontrealSergiy** [comment]
We normally upload/register dataset, BIDS or traditional to CBRAIN, so it is 'File' from boutiques and CBRAIN point of view. In your Brainstorm boutiques descriptor BIDS is still String. 

I understand that BIDS folder is actually file and subject subfolder collection everywhere else, yet for some reason boutiques and CBRAIN terminology is special. Perhaps, in early CBRAIN only individual files could be uploaded/registered as separate entities, and then folder registering/upload came as afterthought. Maybe we should just call it 'File or Folder' or 'Data' instead of File, but somehow majority of our users accepted our type system.

I am not sure 'path to' is most appropriate within CBRAIN for either of BIDS or pipeline json. In CBRAIN we have more or less flat collections (aka groups or projects) of datasets and/or files. I would keep just BIDS dataset as descriptor/label or add more details what kind of data it contains (brain images? megs? eggs? ieggs...), if you have good idea

PS. I guess I should warn that for efficiency and ux reason we handle BIDS apps even in somewhat more convoluted way, especially for participant level analysis. E.g. we allow user upload to CBRAIN only selected subset of subjects, though it is achieved using special cbrain field, without altering the main part of the body of the boutiques descriptor, so perhaps we can discuss need for optimisation latter on. And it continues to evolve as we get more and more requirements from paying users. Yours though does NOT looks as BIDS app though so I am not sure is it relevant here.

**Comment by CorentinLabelle** [comment]
@christinerogers 

> how soon can you update your tool's code to match?

The tool's code does not have to be modified. The modification to the boutique descriptor was done to match the boutique terminology.

> Corentin can you confirm what happens when you run your output on the BIDS Validator and let us know?

Yes, I will test the output and get back to you.

@MontrealSergiy 

Thanks a lot for the clarification. I changed the type and description of both inputs (they are of type 'File'). The updated JSON descriptor is [here](https://github.com/CorentinLabelle/Brainstorm-Tool/blob/main/cbrain_implementation/boutique_descriptor/bst-tool.json). I tried replacing the boutique descriptor with the command `bosh publish --sandbox --replace` but I get an error saying `ERROR (404) Could not delete old file`. Do you know why ? I'll look into that and get back to you when it is replaced.

**Comment by MontrealSergiy** [comment]
now, since pipeline is file rather that path, remove json from the command line template

`"command-line": "bash run_bst_tool.sh [MATLABROOT] [BIDS_DIRECTORY] [PIPELINE_PATH].json",`

otherwise you will get double json file extension in command line

![Screenshot from 2023-04-14 15-06-00](https://user-images.githubusercontent.com/11949081/232138588-b36cc8c0-c063-46f4-9f23-36139e6f7d38.png)

few minor and a bit unrelated issues 

a)  [MATLABROOT] should be replaced with a specific value (or maybe a system variable to be defined in the container, if you not sure what it would be)

b) The boutiques contains windows end of line characters which might create issues in linux systems like cbrain.
you can use online tool https://toolslick.com/conversion/text/dos-to-unix to convert boutiques to unix endlines

c) is doi correct?

**Comment by CorentinLabelle** [comment]
> otherwise you will get double json file extension in command line

Oops sorry. I changed it!

a) Thanks for the comment, I'll add that!

b) I converted the JSON descriptor to unix endlines. Let me know if it is OK.

c) The DOI is correct. The first time, I published the tool twice (by mistake...). I tried replacing one and/or the other by changing the DOI in the JSON descriptor, but in botch cases I get the same error.

**Comment by MontrealSergiy** [comment]
Why https://doi.org/10.5072/zenodo.1182898 does not resolve?

**Comment by CorentinLabelle** [comment]
It seems like the descriptor that I updated cannot be found. I think it might be related to this closed [issue](https://github.com/boutiques/boutiques/issues/523) (and this [one](https://github.com/boutiques/boutiques/pull/526)). It would also explain why I cannot update a descriptor that has already been updated.

I tried modifying the DOI of the descriptor like mentioned in the issues (removing the characters before the `/`) before updating it, but I get the same error.

**Comment by MontrealSergiy** [comment]
I think if doi.org website has no page for given doi, it means that doi is invalid

Maybe upload descriptor manually? Or just delete temporarily until the doi issue is resolved?

**Comment by CorentinLabelle** [comment]
I uploaded the descriptor manually: https://doi.org/10.5281/zenodo.7838649

**Comment by MontrealSergiy** [comment]
that link works
